### ISSUE TITLE
Geocoding artifact in final GUNW outputs

### ISSUE THREAD

**Issue by sssangha** [ACCESS-Cloud-Based-InSAR/DockerizedTopsApp#60]
**Describe the bug**
In some cases, a geocoding artifact manifests along a corner of a frame:
![Screen Shot 2022-05-02 at 12 03 42 PM](https://user-images.githubusercontent.com/13227405/166309170-7c80aec0-dac5-4ed5-b0ce-8d460f238051.png)

**To Reproduce**
1. Run this case out of Tibet as so: ~`isce2_topsapp --reference-scenes S1A_IW_SLC__1SDV_20220320T123241_20220320T123308_042405_050E5B_B237 --secondary-scenes S1A_IW_SLC__1SDV_20220308T123241_20220308T123307_042230_05086E_4B83`~
 `isce2_topsapp --reference-scenes S1A_IW_SLC__1SDV_20220308T123241_20220308T123307_042230_05086E_4B83 --secondary-scenes S1A_IW_SLC__1SDV_20220224T123241_20220224T123308_042055_05027A_A8B5`.
3. View the geocoded products under the `merged` directory

**Proposed bug-fix**
Upon closer inspection, this is an issue inherited from a corrupted `hgt` burst file:
<img width="810" alt="Screen Shot 2022-05-02 at 11 18 45 AM" src="https://user-images.githubusercontent.com/13227405/166309514-41b13baa-5a12-4d05-b34c-99943dd1e4a1.png">

This issue is resolved by rounding the bounds of the input DEM to the nearest integer (as expected internally by ISCE https://github.com/isce-framework/isce2/blob/main/components/isceobj/TopsProc/runVerifyDEM.py#L85-L87):
<img width="795" alt="Screen Shot 2022-05-02 at 11 18 54 AM" src="https://user-images.githubusercontent.com/13227405/166309847-d652181b-cadd-4c4e-99bd-c96916af9a1b.png">

I will reply pointing to a proposed fix in a PR under the `DockerizedTopsApp` repo

**Comment by sssangha** [comment]
Addressed by PR https://github.com/ACCESS-Cloud-Based-InSAR/DockerizedTopsApp/pull/61

**Comment by cmarshak** [comment]
So, in the top right corner of the first image you shared, there is a sliver of the wrapped phase that is output.

![166309170-7c80aec0-dac5-4ed5-b0ce-8d460f238051](https://user-images.githubusercontent.com/5975894/166325034-448cdefe-1e65-4e85-9a1e-194de569f6d4.png)

Can you explain this comment: "Upon closer inspection, this is an issue inherited from a corruption hgt burst file" - is there a description of this somewhere?

**Comment by sssangha** [comment]
@cmarshak yeah, what I was trying to illustrate below is that the `hgt` burst had 0s for a small sliver in the corner. But when I re-ran after adjusting the DEM bounds so that they are buffered and rounded to the nearest integer, we the `hgt` burst is fully populated with non-zero values over this same area.

Thus, the phase field is later properly flattened with non-zero height values and this artifact is averted. Please let me know if this makes more sense?

**Comment by cmarshak** [comment]
So, in short, the DEM buffer needs to be larger for ISCE2 to work?

And the second screenshots are to demonstrate coverage of the DEM?

**Comment by sssangha** [comment]
That's correct, the DEM buffer need to be adjusted + the bounds are to be rounded to the nearest integer. This is not an issue that consistently manifests as it depends on how far off the original bounds were from the nearest integer.

And the grayscale images are the hgt files derived from the DEM via the `runTopo` step. So the idea is that after making this patch, we obtain full coverage and no longer have a sliver of no-data height values.

**Comment by cmarshak** [comment]
I am really glad we recorded this. I believe this pull request fixed this: https://github.com/ACCESS-Cloud-Based-InSAR/DockerizedTopsApp/pull/61/files

Do you know if we have a DEM containing the given integer bounding box will that be ok or does it have to be _exactly_ an integer. 

a) current example from above PR: `xmin, ymin, xmax, ymax = -128, 37, -127, 38`
b) would the following work? - `xmin, ymin, xmax, ymax = -128.1, 36.9, -126.9, 38.1`

**Comment by dbekaert** [comment]
this has been adressed
