### ISSUE TITLE
Fix Polarization in Metadata and Restrict Processing to VV

### ISSUE THREAD

**Issue by cmarshak** [ACCESS-Cloud-Based-InSAR/DockerizedTopsApp#69]
**Describe the bug**
Currently, the metadata is fixed incorrectly as `HH`.

The topsApp workflow can handle different polarizations using the XML file: https://github.com/isce-framework/isce2/discussions/495

However, the default (at least with VV+VH) is co-pol VV data: https://github.com/isce-framework/isce2/discussions/496

For the `IW` SLC data used, there are a number of different polarizations as indicated [here](https://sentinels.copernicus.eu/web/sentinel/user-guides/sentinel-1-sar/naming-conventions#:~:text=The%20top%2Dlevel%20Sentinel%2D1,separated%20by%20an%20underscore%20(_).&text=The%20Mission%20Identifier%20(MMM)%20denotes,for%20the%20SENTINEL%2D1B%20instrument.).

We tend to restrict to `DV` (or dual VV polarization with `VV+VH`). We should restrict to this.

**To Reproduce**

https://github.com/ACCESS-Cloud-Based-InSAR/DockerizedTopsApp/blob/dev/isce2_topsapp/delivery_prep.py#L143

**Expected behavior**
Throw an error if not `DV`.

**Additional context**
Can make this plugin more flexible later, but rather not have unintended side-effects for operations/submissions.

**Comment by cmarshak** [comment]
Sometimes there are SLCs that are submitted that do not have VV files as in `S1B_IW_SLC__1SDH_20161021T042948_20161021T043018_002600_004644_D5CC` which are `DH` - so we should throw an error.

**Comment by dbekaert** [comment]
Should have enumerator logic for that as well as it impact times-series etc. Should be relative straightforward fix using asfsearch polarization as additional filter for S1. https://docs.asf.alaska.edu/api/keywords/

**Comment by cmarshak** [comment]
Yes - agreed - it should be considered how we submit the jobs, possibly in the API, and even in the plugin and well documented.

**Comment by jhkennedy** [comment]
It should be straightforward to have HyP3 reject HH/HH+HV scenes when you try to submit them by updating the pattern for acceptable input granules at https://github.com/ASFHyP3/hyp3/blob/develop/job_spec/INSAR_ISCE.yml#L14

**Comment by cmarshak** [comment]
Let's coordinate this in the new year - nothing urgent here IMO.
