### ISSUE TITLE
Invalid datetime values in delivery json metadata in v0.2.0

### ISSUE THREAD

**Issue by asjohnston-asf** [ACCESS-Cloud-Based-InSAR/DockerizedTopsApp#79]
GUNW products generated using DockerizedTopsApp v0.2.0 have invalid `sensing_start` and `sensing_stop` values in their `.json` metadata files. This causes these products to be rejected when attempting to ingest them into the ASF archive.

For example, from https://hyp3-a19-jpl-contentbucket-1wfnatpznlg8b.s3.us-west-2.amazonaws.com/819086fb-3fb1-4294-8cb2-c1effb453f52/S1-GUNW-D-R-087-tops-20221204_20221122-161627-00157W_00020N-PP-37a3-v2_0_6.json :

```
"sensing_start": "2022-12-04T16:16:12.000ZZ",
"sensing_stop": "2022-12-04T16:16:42.000ZZ",
```

This is due to a change in [asf_search v5.0.0](https://github.com/asfadmin/Discovery-asf_search/blob/master/CHANGELOG.md#500):
> Timestamps in geojson fields now include an explicit Z time zone indicator.

The new build of DockerizedTopsApp pulled in the new version of asf_search, but also still appends an additional `Z` to the timestamps  at https://github.com/ACCESS-Cloud-Based-InSAR/DockerizedTopsApp/blob/main/isce2_topsapp/delivery_prep.py#L134

**Comment by cmarshak** [comment]
Thank you for basically solving this!
